### ISSUE TITLE
WITHAI_TOKEN

### ISSUE THREAD

**Issue by LustfulAdventurer** [AlloryDante/CatalinaGPT#3]
Hello, i would like to ask you about WITHAI_TOKEN, to be completely honest I dont really know what this token is or how to get it.
I would be glad if you could lend me some assistance with this since your bot seems quite good.

**Comment by AlloryDante** [comment]
Uf, I forgot about this project. WithAI is Wisper AI. Idk why I renamed it that way. Basically its same OpenAI key.

This project is not menteined. Idk if it still works or not.

**Comment by LustfulAdventurer** [comment]
Alright, thanks for the quick response, so if i get this right, OpenAI token and the Wisper token are the same?

**Comment by AlloryDante** [comment]
> Alright, thanks for the quick response, so if i get this right, OpenAI token and the Wisper token are the same?

Yes, I made this so you can track expenses per token (now I regret this decision) :))

**Comment by LustfulAdventurer** [comment]
Well I didnt make it work sadly, still thanks for your help understading the tokens

**Comment by LustfulAdventurer** [comment]
Only thing i get when i try to start it is this

 throw new Error('Could not find access token, learn more at https://wit.ai/docs');
    ^

Error: Could not find access token, learn more at https://wit.ai/docs
    at validate (C:\Users\MPC-001\Desktop\CatalinaGPT-master\node_modules\node-wit\lib\wit.js:200:11)
    at new Wit (C:\Users\MPC-001\Desktop\CatalinaGPT-master\node_modules\node-wit\lib\wit.js:20:35)
    at Object.<anonymous> (C:\Users\MPC-001\Desktop\CatalinaGPT-master\modules\handleVoice.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\MPC-001\Desktop\CatalinaGPT-master\main.js:7:21)

Node.js v18.18.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by AlloryDante** [comment]
Man, I am sorry, the project is discontinued.
Also I suspect that the repo is not up-to-date. The token is provided by https://wit.ai/ and its NOT provided by Wisper AI as I previously said. 

I never managed to make the bot respond to real voice prompts as I got busy. However it responded in the VC if you ask her something (or somebody else). Basically the With.ai part was never used. I think someone else made a working fork of my bot. I will ask him and see if its still supported

**Comment by LustfulAdventurer** [comment]
Thank you

**Comment by AlloryDante** [comment]
> Thank you

U should be able to use it without withai. Keep in mind that this is a selfbot, and its not a normal discord bot.
